package bid.woou.ssm.mapper;

import bid.woou.ssm.pojo.SecRole;
import bid.woou.ssm.pojo.SecRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int countByExample(SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int deleteByExample(SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int insert(SecRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int insertSelective(SecRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    List<SecRole> selectByExample(SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    SecRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") SecRole record, @Param("example") SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByExample(@Param("record") SecRole record, @Param("example") SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByPrimaryKeySelective(SecRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByPrimaryKey(SecRole record);
}