package bid.woou.ssm.mapper;

import bid.woou.ssm.pojo.SecUser;
import bid.woou.ssm.pojo.SecUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int countByExample(SecUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int deleteByExample(SecUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int insert(SecUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int insertSelective(SecUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    List<SecUser> selectByExample(SecUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    SecUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") SecUser record, @Param("example") SecUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByExample(@Param("record") SecUser record, @Param("example") SecUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByPrimaryKeySelective(SecUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByPrimaryKey(SecUser record);
}