package bid.woou.ssm.mapper;

import bid.woou.ssm.pojo.SecUserRole;
import bid.woou.ssm.pojo.SecUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int countByExample(SecUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int deleteByExample(SecUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int insert(SecUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int insertSelective(SecUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    List<SecUserRole> selectByExample(SecUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    SecUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") SecUserRole record, @Param("example") SecUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByExample(@Param("record") SecUserRole record, @Param("example") SecUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByPrimaryKeySelective(SecUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_user_role
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    int updateByPrimaryKey(SecUserRole record);
}