package bid.woou.ssm.pojo;

import java.util.Date;

public class SecRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_role.role_id
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_role.role_name
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_role.created_time
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_role.update_time
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_role.role_id
     *
     * @return the value of sec_role.role_id
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_role.role_id
     *
     * @param roleId the value for sec_role.role_id
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_role.role_name
     *
     * @return the value of sec_role.role_name
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_role.role_name
     *
     * @param roleName the value for sec_role.role_name
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_role.created_time
     *
     * @return the value of sec_role.created_time
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_role.created_time
     *
     * @param createdTime the value for sec_role.created_time
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_role.update_time
     *
     * @return the value of sec_role.update_time
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_role.update_time
     *
     * @param updateTime the value for sec_role.update_time
     *
     * @mbggenerated Wed Jul 05 11:26:28 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}